use hrdb;

SELECT * FROM EMPLOYEES;

SELECT sum(salary) FROM employees;

SELECT avg(salary) FROM employees;

SELECT * FROM EMPLOYEES WHERE SALARY < ( SELECT avg(salary) FROM employees)


SELECT ROUND(123.567838473847,3) FROM EMPLOYEES;

SELECT ROUND(AVG(SALARY),2) FROM EMPLOYEES;

SELECT * FROM EMPLOYEES GROUP BY JOB_ID;

SELECT SUM(SALARY) FROM EMPLOYEES;

SELECT SUM(SALARY) FROM EMPLOYEES WHERE JOB_ID=9;

SELECT SUM(SALARY) FROM EMPLOYEES WHERE JOB_ID=8;

SELECT SUM(SALARY),JOB_ID,COUNT(JOB_ID) FROM EMPLOYEES GROUP BY JOB_ID

COLUMN MENTIONED IN GROUP BY MAY OR MAY NOT COME IN THE SELECT CLAUSE
BUT COLUMN MENTIONED IN THE SELECT CLAUSE MUST COME IN THE GROUP BY CLAUSE


SELECT * FROM JOBS;

CREATE TABLE CUSTOMER_INFO
(
   CUSTID INT,
   CUSTNAME VARCHAR(20),
   CITY VARCHAR(20)
   );
   
   ALTER TABLE CUSTOMER_INFO ALTER COLUMN CUSTID INT NOT NULL;

   ALTER TABLE CUSTOMER_INFO ADD  CONSTRAINT MYCID PRIMARY KEY(CUSTID);


INSERT INTO CUSTOMER_INFO VALUES (1,'JACK','PUNE');
INSERT INTO CUSTOMER_INFO VALUES (2,'JANE','PUNE');
INSERT INTO CUSTOMER_INFO VALUES (3,'JILL','PUNE');

INSERT INTO CUSTOMER_INFO VALUES (4,'AMAR','GOA');
INSERT INTO CUSTOMER_INFO VALUES (5,'AKBAR','GOA');
INSERT INTO CUSTOMER_INFO VALUES (6,'ANTHONY','GOA');


SELECT * FROM CUSTOMER_INFO

TRUNCATE TABLE CUSTOMER_INFO



CREATE TABLE MYCAR
(
  CAR_ID INT,
  MODEL VARCHAR(20)
  );

  ALTER TABLE MYCAR ALTER COLUMN CAR_ID INT NOT NULL;
  ALTER TABLE MYCAR ADD PRIMARY KEY (CAR_ID);


  INSERT INTO MYCAR VALUES (5,'BMW');
  INSERT INTO MYCAR VALUES (6,'MERC');

  CREATE TABLE MY_PURCHASE
  (
    PURCHASEID INT,
	CUSTOMER_ID INT REFERENCES CUSTOMER_INFO(CUSTID),
	CID INT REFERENCES MYCAR(CAR_ID),
	PRICE INT
	);
INSERT INTO MY_PURCHASE VALUES (112,2,6,50100000);
INSERT INTO MY_PURCHASE VALUES (113,2,6,5020000);

SELECT * FROM MY_PURCHASE
	
SELECT * FROM MYCAR


SELECT COUNT(CID) FROM MY_PURCHASE GROUP BY CID;

CREATE TABLE FIRST
(
   COL1 VARCHAR(5)
   );

   INSERT INTO FIRST VALUES ('X');


   
CREATE TABLE SECOND
(
   COL2 VARCHAR(5)
   );

   INSERT INTO SECOND VALUES ('P');
   INSERT INTO SECOND VALUES ('Q');

   SELECT * FROM FIRST

   SELECT * FROM SECOND;


   SELECT * FROM FIRST,SECOND;


   
CREATE TABLE THIRD
(
   COL3 VARCHAR(5)
   );

   INSERT INTO FIRST VALUES ('Y');

   INSERT INTO SECOND VALUES ('R');

   DELETE FROM SECOND WHERE COL2='Q'

   INSERT INTO THIRD VALUES ('R');
   INSERT INTO THIRD VALUES ('S');
   INSERT INTO THIRD VALUES ('T');
   INSERT INTO THIRD VALUES ('U');


   SELECT * FROM FIRST
   SELECT * FROM SECOND;

   SELECT * FROM THIRD;

   SELECT * FROM FIRST,SECOND,THIRD;

   SELECT * FROM CUSTOMER_INFO

   SELECT * FROM MY_PURCHASE

   SELECT COUNT(*),CITY FROM CUSTOMER_INFO, MY_PURCHASE,MYCAR WHERE CUSTID = CUSTOMER_ID AND CAR_ID = CID GROUP BY CITY


   CREATE TABLE BOOKS
   (
      BOOKID INT,
	  BOOKNAME VARCHAR(20),
	  BOOKCOST INT,
	  AID INT
	  );

	  INSERT INTO BOOKS VALUES (1,'JPL',500,1);
	  INSERT INTO BOOKS VALUES (2,'UNIX',400,2);
	  INSERT INTO BOOKS VALUES (3,'DBMS',300,3);
	  INSERT INTO BOOKS VALUES (4,'AWS',300,NULL);


	 
   CREATE TABLE AUTHORS
   (
      AUTHORID INT,
	  AUTHORNAME VARCHAR(20),
	  AUTHORCITY VARCHAR(20),
	  BID INT
	  );

	  INSERT INTO AUTHORS VALUES (55,'JAMES','NJ',1);
	  INSERT INTO AUTHORS VALUES (66,'PETER','ND',2);
	INSERT INTO AUTHORS VALUES (77,'SMITH','NY',3);
	INSERT INTO AUTHORS VALUES (88,'MIKE','PUNE',NULL);

	UPDATE BOOKS SET AID=55 WHERE AID=1;
	UPDATE BOOKS SET AID=66 WHERE AID=2;
	UPDATE BOOKS SET AID=77 WHERE AID=3;


	 SELECT * FROM BOOKS
	 SELECT * FROM AUTHORS

	 -- NATURAL JOIN --
	 SELECT * FROM BOOKS, AUTHORS

	 -- EQUI JOIN --
	 SELECT * FROM BOOKS B, AUTHORS A WHERE B.BOOKID = A.BID;
	 SELECT * FROM BOOKS B JOIN AUTHORS A ON B.BOOKID = A.BID;

	 SELECT * FROM BOOKS B JOIN AUTHORS A ON B.AID = A.AUTHORID


	 SELECT * FROM BOOKS B  JOIN AUTHORS A ON B.BOOKID = A.BID;
	 SELECT * FROM AUTHORS A  JOIN BOOKS B ON B.BOOKID = A.BID;

	 -- OUTER JOIN IS USED FOR UNMATCHED RECORDS -- 

	 SELECT * FROM AUTHORS A LEFT OUTER JOIN BOOKS B ON B.BOOKID = A.BID;
	 SELECT * FROM AUTHORS A RIGHT OUTER JOIN BOOKS B ON B.BOOKID = A.BID;
	 SELECT * FROM AUTHORS A FULL OUTER JOIN BOOKS B ON B.BOOKID = A.BID;
	 

	 CREATE TABLE SALGRADE
	 (
	    LOSAL INT,
		HISAL INT,
		GRADE CHAR(1)
		)
		INSERT INTO SALGRADE VALUES (1000,2000,'C');
INSERT INTO SALGRADE VALUES (3000,5000,'B');
INSERT INTO SALGRADE VALUES (6000,9000,'A');

SELECT * FROM SALGRADE;

CREATE TABLE MYEMP
(
  EMPNO INT,
  ENAME VARCHAR(20),
  SAL INT
  );

  INSERT INTO MYEMP VALUES (1,'JACK',1500);
  INSERT INTO MYEMP VALUES (1,'JACK',1500);
INSERT INTO MYEMP VALUES (2,'JANE',2500);
INSERT INTO MYEMP VALUES (3,'JILL',2700);
INSERT INTO MYEMP VALUES (4,'PETER',6500);
INSERT INTO MYEMP VALUES (5,'SAM',1700);
INSERT INTO MYEMP VALUES (6,'SMITH',4500);

SELECT * FROM MYEMP;
SELECT * FROM SALGRADE;
SELECT EMPNO,ENAME,SAL,GRADE FROM MYEMP,SALGRADE WHERE SAL BETWEEN LOSAL AND HISAL;




